spring.application.name=coffeemanagement

# profile active
spring.profiles.active=dev


# JPA common
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=t=a1df647bb43572db9bcbe6fcbb7d87c872032b8a70b1c82109361e5d09c72a6d