spring.application.name=coffeemanagement

# profile active
spring.profiles.active=dev


# JPA common
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/buensabor_db
spring.datasource.username=postgres
spring.datasource.password=unab2026
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Cambié el puerto para evitar el bloqueo del 8080
server.port=8081